detection:
  svm:
    kernel: gaussian # or linear, polynomial
    degree: 4        # only needed for polynomial kernel
    dataset_path: "C:\\Users\\Student\\Downloads\\data_no_injection"
  nn:
    dataset_path: "C:\\Users\\Student\\Downloads\\data_no_injection"
  cnn:
    dataset_path: "C:\\Users\\Student\\Downloads\\data_no_injection"
  dream:
    dataset_path: "C:\\Users\\Student\\Downloads\\data_no_injection"
    train: true
    epochs: 30
    batch_size: 64
    nz: 100
    lr: 0.0002
    device: "cpu"
    dream: true
    n_images: 16